Rework the initialization of the bash and sh scripts so that they will work correctly when referenced as symbolic links.

diff --git a/wrapper/src/bin/bash.script.in b/wrapper/src/bin/bash.script.in
--- a/wrapper/src/bin/bash.script.in
+++ b/wrapper/src/bin/bash.script.in
@@ -25,9 +25,20 @@ PRIORITY=
 # Do not modify anything beyond this point
 #-----------------------------------------------------------------------------
 
-# Get to the actual location of this script
-SCRIPT_DIR=`dirname $0`
-SCRIPT=`$SCRIPT_DIR/realpath $0`
+# Get the actual location of this script.  Need realpath if symlinked
+if [ ! -z "`find $0 -type l`" ]; then
+    REALPATH="`realpath $0`"
+    if [ "$REALPATH" == "" ]; then
+        echo "The realpath command is required when $0 is a symbolic link!"
+        echo "Please copy the realpath executable from the target directory"
+        echo "to /usr/bin"
+        exit 1
+    else
+        SCRIPT="`dirname $REALPATH`"
+    fi
+else
+    SCRIPT="`dirname $0`"
+fi
 cd `dirname $SCRIPT`
 
 # Find pidof.
