Added a new property, wrapper.anchorfile, which makes it possible to cause the Wrapper to shutdown by deleting an anchor file.

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -27,6 +27,11 @@ PRIORITY=
 # Location of the pid file.
 PIDDIR="./"
 
+# If uncommented, causes the Wrapper to be shutdown using an anchor file.
+#  When launched with the 'start' command, it will also ignore all INT and
+#  TERM signals.
+#IGNORE_SIGNALS=true
+
 # Do not modify anything beyond this point
 #-----------------------------------------------------------------------------
 
@@ -65,6 +70,7 @@ REALPATH=`echo $REALPATH | sed -e 's;:; ;g'`
 cd "`dirname "$REALPATH"`"
 
 # Process ID
+ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
 PIDFILE="$PIDDIR/$APP_NAME.pid"
 pid=""
 
@@ -127,7 +133,12 @@ console() {
     getpid
     if [ "X$pid" = "X" ]
     then
-        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE
+        if [ "X$IGNORE_SIGNALS" = "X" ]
+        then
+            exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE
+        else
+            exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE wrapper.anchorfile=$ANCHORFILE
+        fi
     else
         echo "$APP_LONG_NAME is already running."
         exit 1
@@ -139,7 +150,12 @@ start() {
     getpid
     if [ "X$pid" = "X" ]
     then
-        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE wrapper.daemonize=TRUE
+        if [ "X$IGNORE_SIGNALS" = "X" ]
+        then
+            exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE wrapper.daemonize=TRUE
+        else
+            exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.pidfile=$PIDFILE wrapper.anchorfile=$ANCHORFILE wrapper.ignore_signals=TRUE wrapper.daemonize=TRUE
+        fi
     else
         echo "$APP_LONG_NAME is already running."
         exit 1
@@ -153,13 +169,24 @@ stopit() {
     then
         echo "$APP_LONG_NAME was not running."
     else
-         # Running so try to stop it.
-        kill $pid
-        if [ $? -ne 0 ]
+        if [ "X$IGNORE_SIGNALS" = "X" ]
         then
-            # An explanation for the failure should have been given
-            echo "Unable to stop $APP_LONG_NAME."
-            exit 1
+            # Running so try to stop it.
+            kill $pid
+            if [ $? -ne 0 ]
+            then
+                # An explanation for the failure should have been given
+                echo "Unable to stop $APP_LONG_NAME."
+                exit 1
+            fi
+        else
+            rm $ANCHORFILE
+            if [ -f $ANCHORFILE ]
+            then
+                # An explanation for the failure should have been given
+                echo "Unable to stop $APP_LONG_NAME."
+                exit 1
+            fi
         fi
 
         # We can not predict how long it will take for the wrapper to
