work on 3.5.37

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -18,6 +18,13 @@
 # These settings can be modified to fit the needs of your application
 # Optimized for use with version 3.5.37-a of the Wrapper.
 
+# NOTE - After loading the variables below, the Wrapper will try to locate a
+#  file with the same as this script and having a '.shconf' extension.
+#  If such file exists, it will be executed giving the user a chance to
+#  override the default settings. Having the customized configuration in a
+#  separate '.shconf' file make it easier to upgrade the Wrapper as the current
+#  script file can then be replaced without appplying any modification.
+
 # IMPORTANT - Please always stop and uninstall an application before making
 #             any changes to this file.  Failure to do so could remove the
 #             script's ability to control the application.
@@ -38,7 +45,9 @@
 # Description: @app.description@
 ### END INIT INFO
 
-# Application
+# Application name and long name: If these variables are not set (or left to
+#  the default tokens), APP_NAME will default to the name of the script, then
+#  APP_LONG_NAME will default to the value of APP_NAME.
 APP_NAME="@app.name@"
 APP_LONG_NAME="@app.long.name@"
 
@@ -205,6 +214,50 @@ gettext() {
     fi
 }
 
+resolveIdLocation() {
+    if [ "X$ID_BIN" = "X" ] ; then
+        # On Solaris, the version in /usr/xpg4/bin should be used.
+        ID_BIN="/usr/xpg4/bin/id"
+        if [ ! -x "$ID_BIN" ] ; then
+            ID_BIN="id"
+            result=`command -v id 2>/dev/null`
+            if [ $? -ne 0 ] ; then
+                ID_BIN="/usr/bin/id"
+                if [ ! -x "$ID_BIN" ] ; then
+                    eval echo `gettext 'Unable to locate "id".'`
+                    eval echo `gettext 'Please report this message along with the location of the command on your system.'`
+                    exit 1
+                fi
+            fi
+        fi
+    fi
+}
+
+resolveCurrentUser() {
+    if [ "X$CURRENT_USER" = "X" ] ; then
+        resolveIdLocation
+        CURRENT_USER=`$ID_BIN -u -n 2>/dev/null`
+    fi
+}
+
+resolvePidofLocation() {
+    if [ "X$PIDOF_BIN" = "X" ] ; then
+        PIDOF_BIN="pidof"
+        result=`command -v pidof 2>/dev/null`
+        if [ $? -ne 0 ] ; then
+            PIDOF_BIN="/bin/pidof"
+            if [ ! -x "$PIDOF_BIN" ] ; then
+                PIDOF_BIN="/usr/sbin/pidof"
+                if [ ! -x "$PIDOF_BIN" ] ; then
+                    eval echo `gettext 'Unable to locate "pidof".'`
+                    eval echo `gettext 'Please report this message along with the location of the command on your system.'`
+                    exit 1
+                fi
+            fi
+        fi
+    fi
+}
+
 # check if we are running under Cygwin terminal.
 # Note: on some OS's (for example Solaris, MacOS), -o is not a valid parameter 
 # and it shows an error message. We redirect stderr to null so the error message
@@ -230,9 +283,6 @@ if [ $# -gt 1 ] ; then
         SYSD=1
     fi
 fi
-
-# default location for the service file
-SYSTEMD_SERVICE_FILE="/etc/systemd/system/$APP_NAME.service"
 
 # Required for HP-UX Startup
 if [ `uname -s` = "HP-UX" -o `uname -s` = "HP-UX64" ] ; then
@@ -291,6 +341,27 @@ do
     fi
 done
 
+# Try to source a file with the same filename as the script and with the '.shconf' extension.
+case $REALPATH in
+    *.sh)
+        SHCONF_FILE="$REALPATH" | rev | cut -d"." -f2- | rev
+        ;;
+    *)
+        SHCONF_FILE="$REALPATH"
+        ;;
+esac
+
+SHCONF_FILE="$SHCONF_FILE.shconf"
+
+if [ -f "$SHCONF_FILE" ] ; then
+    if [ ! -x "$SHCONF_FILE" ] ; then
+        # We should stop here because the configuration expected in the shconf file will not be loaded.
+        eval echo `gettext 'Found $SHCONF_FILE but could not execute it. Please make sure that the file has execute permissions.'`
+        exit 1
+    fi
+    . "$SHCONF_FILE"
+fi
+
 # Get the location of the script.
 REALDIR=`dirname "$REALPATH"`
 
@@ -315,21 +386,19 @@ else
 fi
 if [ $CHECK_FOLDER_PERMISSIONS -ne 0 ] ; then
     if [ "X$RUN_AS_USER" != "X" ] ; then
-        CURRENT_USER=$RUN_AS_USER
+        CHECK_USER=$RUN_AS_USER
     else
-        CURRENT_USER=`whoami`
-        if [ $? -ne 0 ] ; then
-            CURRENT_USER=$USER
-        fi
+        resolveCurrentUser
+        CHECK_USER=$CURRENT_USER
     fi
     # Unfortunately the following message will not be translated because currently the Wrapper fails to execute correctly when it can't access to the absolute path.
-    eval echo `gettext 'Failed to access the script using an absolute path. Insufficient permissions may prevent the user \"$CURRENT_USER\" from traversing one of the folders. Please check the following permissions:'`
+    eval echo `gettext 'Failed to access the script using an absolute path. Insufficient permissions may prevent the user \"$CHECK_USER\" from traversing one of the folders. Please check the following permissions:'`
 
     OIFS=$IFS
     IFS='/'
     for DIR in $REALDIR
     do
-        INT_PATH="${INT_PATH%/}/$DIR"
+        INT_PATH="${INT_PATH}/$DIR"
         if [ "$DIR" != "." -a "$DIR" != ".." ] ; then
             ALL_PATHS="${ALL_PATHS} ${INT_PATH}"
             result=`cd "${INT_PATH}" 2>/dev/null`
@@ -366,6 +435,17 @@ if [ "$FIRST_CHAR" != "/" ]
 then
     WRAPPER_CONF=$REALDIR/$WRAPPER_CONF
 fi
+
+# Give default values to $APP_NAME and $APP_LONG_NAME
+if [ "X$APP_NAME" = "X" -o "$APP_NAME" = "@app.name@" ] ; then
+    APP_NAME=`basename -- "$0"`
+fi
+if [ "X$APP_LONG_NAME" = "X" -o "$APP_LONG_NAME" = "@app.long.name@" ] ; then
+    APP_LONG_NAME=$APP_NAME
+fi
+
+# default location for the service file
+SYSTEMD_SERVICE_FILE="/etc/systemd/system/$APP_NAME.service"
 
 # Process ID
 ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
@@ -436,43 +516,6 @@ case "$DIST_OS" in
         DIST_OS="zos"
         ;;
 esac
-
-resolveIdLocation() {
-    if [ "X$ID_BIN" = "X" ] ; then
-        # On Solaris, the version in /usr/xpg4/bin should be used.
-        ID_BIN="/usr/xpg4/bin/id"
-        if [ ! -x "$ID_BIN" ] ; then
-            ID_BIN="id"
-            result=`command -v id 2>/dev/null`
-            if [ $? -ne 0 ] ; then
-                ID_BIN="/usr/bin/id"
-                if [ ! -x "$ID_BIN" ] ; then
-                    eval echo `gettext 'Unable to locate "id".'`
-                    eval echo `gettext 'Please report this message along with the location of the command on your system.'`
-                    exit 1
-                fi
-            fi
-        fi
-    fi
-}
-
-resolvePidofLocation() {
-    if [ "X$PIDOF_BIN" = "X" ] ; then
-        PIDOF_BIN="pidof"
-        result=`command -v pidof 2>/dev/null`
-        if [ $? -ne 0 ] ; then
-            PIDOF_BIN="/bin/pidof"
-            if [ ! -x "$PIDOF_BIN" ] ; then
-                PIDOF_BIN="/usr/sbin/pidof"
-                if [ ! -x "$PIDOF_BIN" ] ; then
-                    eval echo `gettext 'Unable to locate "pidof".'`
-                    eval echo `gettext 'Please report this message along with the location of the command on your system.'`
-                    exit 1
-                fi
-            fi
-        fi
-    fi
-}
 
 # Compare Versions $1<$2=0, $1==$2=1, $1>$2=2
 compareVersions () {
@@ -692,7 +735,24 @@ detectWrapperBinary() {
 #  and look for the 32-bit binary.  If that doesn't exist either then
 #  look for the default.
 WRAPPER_TEST_CMD=""
-detectWrapperBinary "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
+
+BIN_BITS=$DIST_BITS
+if [ ! "$BIN_BITS" = "32" ] ; then
+    # On a 64-bit platform, both Wrapper 32-Bit and 64-Bit can be used.
+    #  Send a request to the Wrapper to know if the license has the 64-bit feature.
+    WRAPPER_CMD_ORIG=$WRAPPER_CMD
+    detectWrapperBinary "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$BIN_BITS"
+    if [ ! -z "$WRAPPER_TEST_CMD" ] ; then
+        "$WRAPPER_CMD" --request_delta_binary_bits "$WRAPPER_CONF" 2>/dev/null
+        if [ $? = 32 ] ; then
+            # License is 32-Bit. Reset and search for 32-Bit Wrapper binaries.
+            WRAPPER_TEST_CMD=""
+            WRAPPER_CMD=$WRAPPER_CMD_ORIG
+            BIN_BITS=32
+        fi
+    fi
+fi
+
 if [ -z "$WRAPPER_TEST_CMD" ] ; then
     detectWrapperBinary "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
 fi
@@ -703,8 +763,8 @@ fi
 
 if [ -z "$WRAPPER_TEST_CMD" ] ; then
     eval echo `gettext 'Unable to locate any of the following binaries:'`
-    outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
-    if [ ! "$DIST_BITS" = "32" ] ; then
+    outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$BIN_BITS"
+    if [ ! "$BIN_BITS" = "32" ] ; then
         outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
     fi
     outputFile "$WRAPPER_CMD"
@@ -830,6 +890,64 @@ prepAdditionalParams() {
     fi
 }
 
+resolveSysLocale() {
+    # First try to get the system encoding from /etc/default/locale.
+    # Note: For some reason, the system encoding stored in /etc/default/locale and the value returned by localectl may differ.
+    #       When using 'localectl set-local', /etc/default/locale is always updated accordingly, but when manually editing /etc/default/locale,
+    #       the output of the command sometimes doesn't get updated. When the values differ, SU uses the same locale as /etc/default/locale,
+    #       so that's why we start trying to get the locale using this method.
+    if [ -f "/etc/default/locale" ] ; then
+        PASS_SYS_LANG=`grep 'LANG=' /etc/default/locale`
+        case "$PASS_SYS_LANG" in
+            LANG=*)
+                PASS_SYS_LANG="$PASS_SYS_LANG "
+                ;;
+            *)
+                PASS_SYS_LANG=""
+                ;;
+        esac
+    fi
+    if [ "X$PASS_SYS_LANG" = "X" ] ; then
+        # Try to get the system encoding using localectl.
+        LOCALECTL_BIN="localectl"
+        result=`command -v $LOCALECTL_BIN 2>/dev/null`
+        if [ $? -ne 0 ] ; then
+            LOCALECTL_BIN="/usr/bin/localectl"
+            if [ ! -x "$LOCALECTL_BIN" ] ; then
+                # Keep the warning for debugging, but don't actually show it because it may be normal for some OS to not have the command. 
+                # echo " WARNING: Could not locate localectl used to get the system locale. The encoding may not be correct when running as $RUN_AS_USER."
+                LOCALECTL_BIN=""
+            fi
+        fi
+        if [ "X$LOCALECTL_BIN" != "X" ] ; then
+            # The first line that localectl outputs should look like this: '    System Locale: n/a'
+            PASS_SYS_LANG=`$LOCALECTL_BIN | grep "System Locale" | awk '{print $3}' 2>/dev/null`
+            case "$PASS_SYS_LANG" in
+                *n/a*)
+                    # No system locale set. Skip.
+                    PASS_SYS_LANG=""
+                    ;;
+                LANG=*)
+                    PASS_SYS_LANG="$PASS_SYS_LANG "
+                    ;;
+                *)
+                    # echo " WARNING: Failed to parse the output of localectl. The encoding may not be correct when running as $RUN_AS_USER.'"
+                    PASS_SYS_LANG=""
+                    ;;
+            esac
+        fi
+    fi
+}
+
+resolveSuLocale() {
+    if [ "X$PASS_SU_LANG" = "X" -a "X$RUN_AS_USER" != "X" ] ; then
+        PASS_SU_LANG=`$SU_BIN - $RUN_AS_USER -c "locale" $SU_OPTS | grep "LANG=" 2>/dev/null`
+        if [ "X$PASS_SU_LANG" != "X" ] ; then
+            PASS_SU_LANG="$PASS_SU_LANG "
+        fi
+    fi
+}
+
 checkUser() {
     # $1 touchLock flag
     # $2.. [command] args
@@ -837,8 +955,8 @@ checkUser() {
     # Check the configured user.  If necessary rerun this script as the desired user.
     if [ "X$RUN_AS_USER" != "X" ]
     then
-        resolveIdLocation
-        if [ "`$ID_BIN -u -n`" = "$RUN_AS_USER" ]
+        resolveCurrentUser
+        if [ "$CURRENT_USER" = "$RUN_AS_USER" ]
         then
             # Already running as the configured user.  Avoid password prompts by not calling su.
             RUN_AS_USER=""
@@ -889,10 +1007,24 @@ checkUser() {
 
         # runuser doesn't transmit signals (such as ctrl+c) to the Wrapper. This causes problem when running as a console.
         # When the Wrapper is launched as a service on RedHat, runuser should be used in preference to su.
+        resolveSysLocale
         if [ -f "/sbin/runuser" -a $COMMAND != "console" ] ; then
-            /sbin/runuser - $RUN_AS_USER -c "\"$REALPATH\" $ADDITIONAL_PARA" $SU_OPTS
+            # Unlike su, runuser doesn't use the default system locale. Force passing it for consistency.
+            if [ "X$PASS_SYS_LANG" = "X" ] ; then
+                # Fallback to the same locale as when using SU (which should be the system encoding).
+                resolveSuLocale
+                PASS_SYS_LANG=$PASS_SU_LANG
+            fi
+            /sbin/runuser - $RUN_AS_USER -c "$PASS_SYS_LANG\"$REALPATH\" $ADDITIONAL_PARA" $SU_OPTS
         else
-            $SU_BIN - $RUN_AS_USER -c "\"$REALPATH\" $ADDITIONAL_PARA" $SU_OPTS
+            # Normally SU should use the default system locale, but make sure it is the case.
+            resolveSuLocale
+            if [ "X$PASS_SU_LANG" != "X" -a "$PASS_SU_LANG" != "$PASS_SYS_LANG" ] ; then
+                PASS_SU_LANG=$PASS_SYS_LANG
+            else
+                PASS_SU_LANG=""
+            fi
+            $SU_BIN - $RUN_AS_USER -c "$PASS_SU_LANG\"$REALPATH\" $ADDITIONAL_PARA" $SU_OPTS
         fi
         RUN_AS_USER_EXITCODE=$?
         
@@ -1251,6 +1383,8 @@ mustBeStoppedOrExit() {
     fi
 }
 
+# Detect if the Wrapper is running
+# Returns 0 if the process is running, otherwise returns 1.
 checkRunning() {
     getpid
     if [ "X$pid" = "X" ] ; then
@@ -1258,7 +1392,9 @@ checkRunning() {
         if [ "X$1" = "X1" ] ; then
             exit 1
         fi
+        return 1
     fi
+    return 0
 }
 
 
@@ -1416,6 +1552,12 @@ upstartRestart() {
         
         startwait
     fi
+}
+
+upstartRemove() {
+    stopit "0"
+    eval echo `gettext ' Removing $APP_LONG_NAME daemon from upstart...'`
+    rm "/etc/init/${APP_NAME}.conf"
 }
 
 # Method to check if systemd is running.
@@ -1628,16 +1770,8 @@ start() {
  
 stopit() {
     # $1 exit if down flag
-    
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        eval echo `gettext '$APP_LONG_NAME is not running.'`
-        if [ "X$1" = "X1" ]
-        then
-            exit 1
-        fi
-    else
+    checkRunning $1
+    if [ $? -eq 0 ] ; then
         # The daemon should be running.
         eval echo `gettext 'Stopping $APP_LONG_NAME...'`
 
@@ -2226,9 +2360,7 @@ removedaemon() {
             elif [ $installedStatus -eq 2 ] ; then
                 systemdRemove
             elif [ $installedStatus -eq 3 ] ; then
-                stopit "0"
-                eval echo `gettext ' Removing $APP_LONG_NAME daemon from upstart...'`
-                rm "/etc/init/${APP_NAME}.conf"
+                upstartRemove
             else
                 eval echo `gettext ' The $APP_LONG_NAME daemon is not currently installed.'`
                 exit 1
@@ -2256,9 +2388,7 @@ removedaemon() {
             elif [ $installedStatus -eq 2 ] ; then
                 systemdRemove
             elif [ $installedStatus -eq 3 ] ; then
-                stopit "0"
-                eval echo `gettext ' Removing $APP_LONG_NAME daemon from upstart...'`
-                rm "/etc/init/${APP_NAME}.conf"
+                upstartRemove
             else
                 eval echo `gettext ' The $APP_LONG_NAME daemon is not currently installed.'`
                 exit 1
