3.5.34 Release

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -134,11 +134,6 @@ SU_BIN=su
 #  the '-s' option.
 #SU_OPTS="-s /bin/bash"
 
-# Set the full path to the 'id' command.
-# For example:
-#  ID_BIN=/usr/bin/id
-ID_BIN=id
-
 # By default we show a detailed usage block.  Uncomment to show brief usage.
 #BRIEF_USAGE=true
 
@@ -371,36 +366,16 @@ case "$DIST_OS" in
 esac
 
 resolveIdLocation() {
-    # Resolve the location of the 'id' command if not set above.
-    if [ ! -x "$ID_BIN" ]
-    then
+    if [ "X$ID_BIN" = "X" ] ; then
+        # On Solaris, the version in /usr/xpg4/bin should be used.
         ID_BIN="/usr/xpg4/bin/id"
-        if [ ! -x "$ID_BIN" ]
-        then
-            ID_BIN="/usr/bin/id"
-            if [ ! -x "$ID_BIN" ]
-            then
-                eval echo `gettext 'Unable to locate "id".'`
-                eval echo `gettext 'Please report this message along with the location of the command on your system.'`
-                exit 1
-            fi
-        fi
-    fi
-}
-
-resolvePidofLocation() {
-    if [ ! -x "$PIDOF_BIN" ]
-    then
-        PIDOF_BIN="pidof"
-        if [ ! -x "$PIDOF_BIN" ]
-        then
-            PIDOF_BIN="/bin/pidof"
-            if [ ! -x "$PIDOF_BIN" ]
-            then
-                PIDOF_BIN="/usr/sbin/pidof"
-                if [ ! -x "$PIDOF_BIN" ]
-                then
-                    eval echo `gettext 'Unable to locate "pidof".'`
+        if [ ! -x "$ID_BIN" ] ; then
+            ID_BIN="id"
+            result=`command -v id 2>/dev/null`
+            if [ $? -ne 0 ] ; then
+                ID_BIN="/usr/bin/id"
+                if [ ! -x "$ID_BIN" ] ; then
+                    eval echo `gettext 'Unable to locate "id".'`
                     eval echo `gettext 'Please report this message along with the location of the command on your system.'`
                     exit 1
                 fi
@@ -409,18 +384,19 @@ resolvePidofLocation() {
     fi
 }
 
-resolveInitctlLocation() {
-    if [ ! -x "$INITCTL_BIN" ]
-    then
-        INITCTL_BIN="initctl"
-        if [ ! -x "$INITCTL_BIN" ]
-        then
-            INITCTL_BIN="/sbin/initctl"
-            if [ ! -x "$INITCTL_BIN" ]
-            then
-                eval echo `gettext 'Unable to locate "initctl".'`
-                eval echo `gettext 'Please report this message along with the location of the command on your system.'`
-                exit 1
+resolvePidofLocation() {
+    if [ "X$PIDOF_BIN" = "X" ] ; then
+        PIDOF_BIN="pidof"
+        result=`command -v pidof 2>/dev/null`
+        if [ $? -ne 0 ] ; then
+            PIDOF_BIN="/bin/pidof"
+            if [ ! -x "$PIDOF_BIN" ] ; then
+                PIDOF_BIN="/usr/sbin/pidof"
+                if [ ! -x "$PIDOF_BIN" ] ; then
+                    eval echo `gettext 'Unable to locate "pidof".'`
+                    eval echo `gettext 'Please report this message along with the location of the command on your system.'`
+                    exit 1
+                fi
             fi
         fi
     fi
@@ -1087,7 +1063,7 @@ launchdtrap() {
     exit 
 }
 
-waitforwrapperstop() {
+waitForWrapperStop() {
     getpid
     while [ "X$pid" != "X" ] ; do
         sleep 1
@@ -1112,7 +1088,7 @@ launchinternal() {
     # launchd expects that this script stay up and running so we need to do our own monitoring of the Wrapper process.
     if [ $WAIT_FOR_STARTED_STATUS = true ]
     then
-        waitforwrapperstop
+        waitForWrapperStop
     fi
 }
 
@@ -1211,11 +1187,13 @@ mustBeStoppedOrExit() {
     fi
 }
 
-mustBeRunningOrExit() {
+checkRunning() {
     getpid
     if [ "X$pid" = "X" ] ; then
         eval echo `gettext '$APP_LONG_NAME is not running.'`
-        exit 1
+        if [ "X$1" = "X1" ] ; then
+            exit 1
+        fi
     fi
 }
 
@@ -1224,7 +1202,6 @@ macosxStart() {
     mustBeRootOrExit
     mustBeStoppedOrExit
     
-    # The daemon has been installed.
     eval echo `gettext 'Starting $APP_LONG_NAME with launchd...'`
     
     # If the daemon was just installed, it may not be loaded.
@@ -1243,9 +1220,9 @@ macosxStart() {
 
 macosxStop() {
     mustBeRootOrExit
-    mustBeRunningOrExit
+    # The daemon must be running.
+    checkRunning "1"
     
-    # The daemon should be running.
     eval echo `gettext 'Stopping $APP_LONG_NAME...'`
     
     if [ "$MACOSX_KEEP_RUNNING" = "true" ] ; then
@@ -1261,9 +1238,8 @@ macosxStop() {
 
 macosxRestart() {
     mustBeRootOrExit
-    mustBeRunningOrExit
+    checkRunning $1
 
-    # The daemon should be running.
     eval echo `gettext 'Restarting $APP_LONG_NAME...'`
 
     if [ "$MACOSX_KEEP_RUNNING" = "true" ] ; then
@@ -1285,7 +1261,15 @@ upstartDetection() {
         return 1
     fi
     
-    resolveInitctlLocation
+    INITCTL_BIN="initctl"
+    result=`command -v $INITCTL_BIN 2>/dev/null`
+    if [ $? -ne 0 ] ; then
+        INITCTL_BIN="/sbin/initctl"
+        if [ ! -x "$INITCTL_BIN" ] ; then
+            return 1
+        fi
+    fi
+    
     result=`$INITCTL_BIN version 2>/dev/null`
     if [ $? -eq 0 ] ; then
         # if the word "upstart" is in the result, then we assume upstart is installed.
@@ -1334,7 +1318,6 @@ upstartStart() {
     mustBeRootOrExit
     mustBeStoppedOrExit
 
-    # The daemon has been installed.
     eval echo `gettext 'Starting $APP_LONG_NAME with upstart...'`
     
     /sbin/start ${APP_NAME}
@@ -1344,9 +1327,9 @@ upstartStart() {
 
 upstartStop() {
     mustBeRootOrExit
-    mustBeRunningOrExit
+    # The daemon must be running.
+    checkRunning "1"
 
-    # The daemon should be running.
     eval echo `gettext 'Stopping $APP_LONG_NAME...'`
     
     /sbin/stop ${APP_NAME}
@@ -1354,14 +1337,21 @@ upstartStop() {
 
 upstartRestart() {
     mustBeRootOrExit
-    mustBeRunningOrExit
+    checkRunning $1
 
-    # The daemon should be running.
-    eval echo `gettext 'Restarting $APP_LONG_NAME...'`
-    
-    /sbin/restart ${APP_NAME}
+    if [ "X$pid" = "X" ] ; then
+        # Don't use /sbin/restart because it requires the daemon to be running.
+        #  We want to match with other systems behaviour which is to restart the
+        #  daemon even if it was not running.
+        upstartStart
+    else
+        # The daemon was running
+        eval echo `gettext 'Restarting $APP_LONG_NAME...'`
+
+        /sbin/restart ${APP_NAME}
         
-    startwait
+        startwait
+    fi
 }
 
 # Method to check if systemd is running.
@@ -1427,7 +1417,6 @@ systemdStart() {
         exit 1
     fi
     
-    # The daemon has been installed.
     eval echo `gettext 'Starting $APP_LONG_NAME with systemd...'`
 
     systemctl start $APP_NAME
@@ -1441,9 +1430,9 @@ systemdStart() {
 
 systemdStop() {
     # Don't do mustBeRootOrExit because systemd will ask for the password when not root
-    mustBeRunningOrExit
+    # The daemon must be running.
+    checkRunning "1"
 
-    # The daemon should be running.
     eval echo `gettext 'Stopping $APP_LONG_NAME...'`
 
     systemctl stop $APP_NAME
@@ -1455,9 +1444,8 @@ systemdStop() {
 
 systemdRestart() {
     # Don't do mustBeRootOrExit because systemd will ask for the password when not root
-    mustBeRunningOrExit
+    checkRunning $1
 
-    # The daemon should be running.
     eval echo `gettext 'Restarting $APP_LONG_NAME...'`
 
     systemctl restart $APP_NAME
@@ -1510,12 +1498,9 @@ srcInstall() {
 }
 
 srcStart() {
-    if [ "$1" != 'skipCheck' ] ; then
-        mustBeRootOrExit
-        mustBeStoppedOrExit
-    fi
+    mustBeRootOrExit
+    mustBeStoppedOrExit
 
-    # The daemon has been installed.
     eval echo `gettext 'Starting $APP_LONG_NAME with SRC...'`
 
     startsrc -s "${APP_NAME}"
@@ -1528,12 +1513,10 @@ srcStart() {
 }
 
 srcStop() {
-    if [ "$1" != 'skipCheck' ] ; then
-        mustBeRootOrExit
-        mustBeRunningOrExit
-    fi
+    mustBeRootOrExit
+    # The daemon must be running.
+    checkRunning "1"
 
-    # The daemon should be running.
     eval echo `gettext 'Stopping $APP_LONG_NAME...'`
 
     stopsrc -s "${APP_NAME}"
@@ -1545,29 +1528,27 @@ srcStop() {
 
 srcRestart() {
     mustBeRootOrExit
-    mustBeRunningOrExit
+    checkRunning $1
 
-    # The daemon should be running.
-    eval echo `gettext 'Restarting $APP_LONG_NAME...'`
-
-    srcStop 'skipCheck'
-    srcStart 'skipCheck'
+    if [ "X$pid" != "X" ] ; then
+        # The daemon was running. Stop it first.
+        eval echo `gettext 'Restarting $APP_LONG_NAME...'`
+        srcStop
+        waitForWrapperStop
+    fi
+    srcStart
 }
 
 start() {
+    mustBeStoppedOrExit
+    
     eval echo `gettext 'Starting $APP_LONG_NAME...'`
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        prepAdditionalParams "$@"
+    
+    prepAdditionalParams "$@"
 
-        # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.34 $ADDITIONAL_PARA"
-        eval $COMMAND_LINE
-    else
-        eval echo `gettext '$APP_LONG_NAME is already running.'`
-        exit 1
-    fi
+    # The string passed to eval must handles spaces in paths correctly.
+    COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.34 $ADDITIONAL_PARA"
+    eval $COMMAND_LINE
     
     startwait
 }
@@ -2117,6 +2098,32 @@ startdaemon() {
     fi
 }
 
+restartdaemon() {
+    if [ "$DIST_OS" = "macosx" -a -f "/Library/LaunchDaemons/${APP_PLIST}" ] ; then
+        macosxRestart $1
+    elif [ "$DIST_OS" = "linux" -a -n "$USE_UPSTART" ] && [ -f "/etc/init/${APP_NAME}.conf" ] ; then
+        upstartRestart $1
+    elif [ "$DIST_OS" = "linux" -a -n "$USE_SYSTEMD" -a -z "$SYSD" ] && [ -f "${SYSTEMD_SERVICE_FILE}" ] ; then
+        systemdRestart $1
+    elif [ "$DIST_OS" = "aix" -a -n "$USE_SRC" ] && [ -n "`/usr/bin/lssrc -S -s $APP_NAME`" ] ; then
+        srcRestart $1
+    else
+        checkUser touchlock "$COMMAND"
+
+        checkRunning $1
+        if [ "X$pid" != "X" ] ; then
+            # The daemon was running. Stop it first.
+            eval echo `gettext 'Restarting $APP_LONG_NAME...'`
+            stopit $1
+        fi
+        shift
+        if [ ! -n "$FIXED_COMMAND" ] ; then
+            shift
+        fi
+        start "$@"
+    fi
+}
+
 removedaemon() {
     mustBeRootOrExit
     
@@ -2513,35 +2520,12 @@ docommand() {
     
         'restart')
             setServiceManagementTool
-            if [ "$DIST_OS" = "macosx" -a -f "/Library/LaunchDaemons/${APP_PLIST}" ] ; then
-                macosxRestart
-            elif [ "$DIST_OS" = "linux" -a -n "$USE_UPSTART" ] && [ -f "/etc/init/${APP_NAME}.conf" ] ; then
-                upstartRestart
-            elif [ "$DIST_OS" = "linux" -a -n "$USE_SYSTEMD" -a -z "$SYSD" ] && [ -f "${SYSTEMD_SERVICE_FILE}" ] ; then
-                systemdRestart
-            elif [ "$DIST_OS" = "aix" -a -n "$USE_SRC" ] && [ -n "`/usr/bin/lssrc -S -s $APP_NAME`" ] ; then
-                srcRestart
-            else
-                if [ -n "$SMF" ] ; then
-                    shift
-                fi
-                checkUser touchlock "$COMMAND"
-                if [ ! -n "$FIXED_COMMAND" ] ; then
-                    shift
-                fi
-                stopit "0"
-                start "$@"
-            fi
+            restartdaemon "0" "$@"
             ;;
     
         'condrestart')
             setServiceManagementTool
-            checkUser touchlock "$COMMAND"
-            if [ ! -n "$FIXED_COMMAND" ] ; then
-                shift
-            fi
-            stopit "1"
-            start "$@"
+            restartdaemon "1" "$@"
             ;;
     
         'pause')
