Work on 3.5.25 fixing a few issues.

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -97,6 +97,9 @@ WAIT_FOR_STARTED_TIMEOUT=120
 # flag for using upstart when installing (rather than init.d rc.d)
 USE_UPSTART=
 
+# flag for using systemd when installing
+USE_SYSTEMD=
+
 # When installing on On Mac OSX platforms, the following domain will be used to
 #  prefix the plist file name.
 PLIST_DOMAIN=org.tanukisoftware.wrapper
@@ -297,8 +300,12 @@ then
     APP_PLIST_BASE=${PLIST_DOMAIN}.${APP_NAME}
     APP_PLIST=${APP_PLIST_BASE}.plist
 else
-    DIST_ARCH=
-    DIST_ARCH=`uname -p 2>/dev/null | $TREXE "[A-Z]" "[a-z]" | $TREXE -d ' '`
+    if [ "$DIST_OS" = "linux" ]
+    then
+        DIST_ARCH=
+    else
+        DIST_ARCH=`uname -p 2>/dev/null | $TREXE "[A-Z]" "[a-z]" | $TREXE -d ' '`
+    fi
     if [ "X$DIST_ARCH" = "X" ]
     then
         DIST_ARCH="unknown"
@@ -1104,6 +1111,15 @@ status() {
     fi
 }
 
+# Make sure APP_NAME is less than 14 characters, otherwise in AIX, the command
+# "lsitab" will fail
+validateAppNameLength() {
+    if [ ${#APP_NAME} -gt 14 ] ; then
+        eval echo `gettext ' APP_NAME (${APP_NAME}) must be less than 14 characters long'`
+        exit 1
+    fi
+}
+
 installUpstart() {
     eval echo `gettext ' Installing the $APP_LONG_NAME daemon using upstart..'`
     if [ -f "${REALDIR}/${APP_NAME}.install" ] ; then 
@@ -1118,6 +1134,30 @@ installUpstart() {
         echo "stop on runlevel [!2345]" >> "/etc/init/${APP_NAME}.conf"
         echo "env LANG=${LANG}" >> "/etc/init/${APP_NAME}.conf"
        echo "exec \"${REALPATH}\" upstartinternal" >> "/etc/init/${APP_NAME}.conf"
+    fi
+}
+
+installSystemd() {
+    eval echo `gettext ' Installing the $APP_LONG_NAME daemon using systemd..'`
+    if [ -f "${REALDIR}/${APP_NAME}.service" ] ; then 
+        eval echo `gettext ' a custom service file ${APP_NAME}.service found'`
+        cp "${REALDIR}/${APP_NAME}.service" "/etc/systemd/system/${APP_NAME}.service"
+    else
+        eval echo `gettext ' creating default service file..'`
+        echo "[Unit]"                            > "/etc/systemd/system/${APP_NAME}.service"
+        echo "Description=${APP_LONG_NAME}"     >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "After=syslog.target"              >> "/etc/systemd/system/${APP_NAME}.service"
+        echo ""                                 >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "[Service]"                        >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "Type=forking"                     >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "ExecStart=\"${REALPATH}\" start"  >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "ExecStop=\"${REALPATH}\" stop"    >> "/etc/systemd/system/${APP_NAME}.service"
+        echo ""                                 >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "[Install]"                        >> "/etc/systemd/system/${APP_NAME}.service"
+        echo "WantedBy=multi-user.target"       >> "/etc/systemd/system/${APP_NAME}.service"
+
+        systemctl daemon-reload
+        systemctl enable "${APP_NAME}.service"
     fi
 }
 
@@ -1148,6 +1188,8 @@ installdaemon() {
                 if [ -f "/etc/init.d/$APP_NAME" -o -L "/etc/init.d/$APP_NAME" -o -f "/etc/init/${APP_NAME}.conf" ] ; then
                     eval echo `gettext ' The $APP_LONG_NAME daemon is already installed.'`
                     exit 1
+                elif [ -n "$USE_SYSTEMD" -a -d "/etc/systemd" ] ; then
+                        installSystemd
                 else
                     if [ -n "$USE_UPSTART" -a -d "/etc/init" ] ; then
                         installUpstart
@@ -1163,6 +1205,8 @@ installdaemon() {
                 if [ -f "/etc/init.d/$APP_NAME" -o -L "/etc/init.d/$APP_NAME" ] ; then
                     eval echo `gettext ' The $APP_LONG_NAME daemon is already installed.'`
                     exit 1
+                elif [ -n "$USE_SYSTEMD" -a -d "/etc/systemd" ] ; then
+                        installSystemd
                 else
                     eval echo `gettext ' Installing the $APP_LONG_NAME daemon..'`
                     ln -s "$REALPATH" "/etc/init.d/$APP_NAME"
@@ -1174,7 +1218,9 @@ installdaemon() {
                     eval echo `gettext ' The $APP_LONG_NAME daemon is already installed.'`
                     exit 1
                 else
-                    if [ -n "$USE_UPSTART" -a -d "/etc/init" ] ; then
+                    if [ -n "$USE_SYSTEMD" -a -d "/etc/systemd" ] ; then
+                        installSystemd
+                    elif [ -n "$USE_UPSTART" -a -d "/etc/init" ] ; then
                         installUpstart
                     else 
                         eval echo `gettext ' Installing the $APP_LONG_NAME daemon using init.d..'`
@@ -1187,7 +1233,7 @@ installdaemon() {
                 if [ -f "/etc/init.d/$APP_NAME" -o -L "/etc/init.d/$APP_NAME" ] ; then
                     eval echo `gettext ' The $APP_LONG_NAME daemon is already installed.'`
                     exit 1
-                else
+                # "lsitab" will failse
                     eval echo `gettext ' Installing the $APP_LONG_NAME daemon..'`
                     ln -s "$REALPATH" /etc/init.d/$APP_NAME
                     for i in `ls "/etc/rc3.d/K"??"$APP_NAME_LOWER" "/etc/rc5.d/K"??"$APP_NAME_LOWER" "/etc/rc3.d/S"??"$APP_NAME_LOWER" "/etc/rc5.d/S"??"$APP_NAME_LOWER" 2>/dev/null` ; do
@@ -1217,6 +1263,7 @@ installdaemon() {
             fi
         elif [ "$DIST_OS" = "aix" ] ; then
             eval echo `gettext 'Detected AIX:'`
+            validateAppNameLength
             if [ -f "/etc/rc.d/init.d/$APP_NAME" ] ; then
                 eval echo `gettext ' The $APP_LONG_NAME daemon is already installed as rc.d script.'`
                 exit 1
@@ -1354,6 +1401,12 @@ removedaemon() {
                     /sbin/chkconfig "$APP_NAME" off
                     /sbin/chkconfig --del "$APP_NAME"
                     rm -f "/etc/init.d/$APP_NAME"
+                elif [ -f "/etc/systemd/system/${APP_NAME}.service" ] ; then
+                    stopit "0"
+                    eval echo `gettext ' Removing $APP_LONG_NAME daemon from systemd...'`
+                    systemctl stop "${APP_NAME}.service"
+                    rm "/etc/systemd/system/${APP_NAME}.service"
+                    systemctl daemon-reload
                 elif [ -f "/etc/init/${APP_NAME}.conf" ] ; then
                     stopit "0"
                     eval echo `gettext ' Removing $APP_LONG_NAME daemon from upstart...'`
@@ -1369,6 +1422,12 @@ removedaemon() {
                     eval echo `gettext ' Removing $APP_LONG_NAME daemon...'`
                     insserv -r "/etc/init.d/$APP_NAME"
                     rm -f "/etc/init.d/$APP_NAME"
+                elif [ -f "/etc/systemd/system/${APP_NAME}.service" ] ; then
+                    stopit "0"
+                    eval echo `gettext ' Removing $APP_LONG_NAME daemon from systemd...'`
+                    systemctl stop "${APP_NAME}.service"
+                    rm "/etc/systemd/system/${APP_NAME}.service"
+                    systemctl daemon-reload
                 else
                     eval echo `gettext ' The $APP_LONG_NAME daemon is not currently installed.'`
                     exit 1
@@ -1380,6 +1439,12 @@ removedaemon() {
                     eval echo `gettext ' Removing $APP_LONG_NAME daemon from init.d...'`
                     update-rc.d -f "$APP_NAME" remove
                     rm -f "/etc/init.d/$APP_NAME"
+                elif [ -f "/etc/systemd/system/${APP_NAME}.service" ] ; then
+                    stopit "0"
+                    eval echo `gettext ' Removing $APP_LONG_NAME daemon from systemd...'`
+                    systemctl stop "${APP_NAME}.service"
+                    rm "/etc/systemd/system/${APP_NAME}.service"
+                    systemctl daemon-reload
                 elif [ -f "/etc/init/${APP_NAME}.conf" ] ; then
                     stopit "0"
                     eval echo `gettext ' Removing $APP_LONG_NAME daemon from upstart...'`
@@ -1415,6 +1480,7 @@ removedaemon() {
             fi
         elif [ "$DIST_OS" = "aix" ] ; then
             eval echo `gettext 'Detected AIX:'`
+            validateAppNameLength
             if [ -f "/etc/rc.d/init.d/$APP_NAME" -o -L "/etc/rc.d/init.d/$APP_NAME" -o -n "`/usr/sbin/lsitab $APP_NAME`" -o -n "`/usr/bin/lssrc -S -s $APP_NAME`" ] ; then
                 stopit "0"
                 eval echo `gettext ' Removing $APP_LONG_NAME daemon...'`
