Modify the shell script so it does not prompt for a password simply to show the usage.

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -83,37 +83,6 @@ REALPATH=`echo $REALPATH | sed -e 's;:; ;g'`
 cd "`dirname "$REALPATH"`"
 REALDIR=`pwd`
 
-
-# Check the configured user.  If necessary rerun this script as the desired user.
-if [ "X$RUN_AS_USER" != "X" ]
-then
-    # Resolve the location of the 'id' command
-    IDEXE="/usr/xpg4/bin/id"
-    if [ ! -x $IDEXE ]
-    then
-        IDEXE="/usr/bin/id"
-        if [ ! -x $IDEXE ]
-        then
-            echo "Unable to locate 'id'."
-            echo "Please report this message along with the location of the command on your system."
-            exit 1
-        fi
-    fi
-
-    if [ "`$IDEXE -u -n`" = "$RUN_AS_USER" ]
-    then
-        # Already running as the configured user.  Avoid password prompts by not calling su.
-        RUN_AS_USER=""
-    fi
-fi
-if [ "X$RUN_AS_USER" != "X" ]
-then
-    # Still want to change users, recurse.  This means that the user will only be
-    #  prompted for a password once.
-    su -m $RUN_AS_USER -c "$REALPATH $1"
-    exit 0
-fi
-
 # If the PIDDIR is relative, set its value relative to the full REALPATH to avoid problems if
 #  the working directory is later changed.
 FIRST_CHAR=`echo $PIDDIR | cut -c1,1`
@@ -159,6 +128,38 @@ then
 else
     CMDNICE="nice -$PRIORITY"
 fi
+
+checkUser() {
+    # Check the configured user.  If necessary rerun this script as the desired user.
+    if [ "X$RUN_AS_USER" != "X" ]
+    then
+        # Resolve the location of the 'id' command
+        IDEXE="/usr/xpg4/bin/id"
+        if [ ! -x $IDEXE ]
+        then
+            IDEXE="/usr/bin/id"
+            if [ ! -x $IDEXE ]
+            then
+                echo "Unable to locate 'id'."
+                echo "Please report this message along with the location of the command on your system."
+                exit 1
+            fi
+        fi
+    
+        if [ "`$IDEXE -u -n`" = "$RUN_AS_USER" ]
+        then
+            # Already running as the configured user.  Avoid password prompts by not calling su.
+            RUN_AS_USER=""
+        fi
+    fi
+    if [ "X$RUN_AS_USER" != "X" ]
+    then
+        # Still want to change users, recurse.  This means that the user will only be
+        #  prompted for a password once.
+        su -m $RUN_AS_USER -c "$REALPATH $1"
+        exit 0
+    fi
+}
 
 getpid() {
     if [ -f $PIDFILE ]
@@ -324,27 +325,33 @@ dump() {
 case "$1" in
 
     'console')
+        checkUser
         console
         ;;
 
     'start')
+        checkUser
         start
         ;;
 
     'stop')
+        checkUser
         stopit
         ;;
 
     'restart')
+        checkUser
         stopit
         start
         ;;
 
     'status')
+        checkUser
         status
         ;;
 
     'dump')
+        checkUser
         dump
         ;;
 
