Work on 3.4.1 release

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -175,19 +175,21 @@ LOCKFILE="$LOCKDIR/$APP_NAME"
 pid=""
 
 # Resolve the location of the 'ps' command
-
-    PSEXE="/usr/bin/ps"
+PSEXE="/usr/ucb/ps"
     if [ ! -x "$PSEXE" ]
     then
-        PSEXE="/bin/ps"
+        PSEXE="/usr/bin/ps"
         if [ ! -x "$PSEXE" ]
         then
-            echo "Unable to locate 'ps'."
-            echo "Please report this message along with the location of the command on your system."
-            exit 1
+            PSEXE="/bin/ps"
+            if [ ! -x "$PSEXE" ]
+            then
+                echo "Unable to locate 'ps'."
+                echo "Please report this message along with the location of the command on your system."
+                exit 1
+            fi
         fi
     fi
-    
 
 # Resolve the os
 DIST_OS=`uname -s | tr [A-Z] [a-z] | tr -d ' '`
@@ -505,7 +507,36 @@ getpid() {
                         pidtest=`$PSEXE -ww -p $pid -o command | grep "$WRAPPER_CMD" | tail -1`
                         ;;
                     'solaris')
-                        pidtest=`pargs $pid | grep "$WRAPPER_CMD" | tail -1`
+                        if [ -f "/usr/bin/pargs" ]
+                        then
+                            pidtest=`pargs $pid | grep "$WRAPPER_CMD" | tail -1`
+                        else
+                            case "$PSEXE" in
+                            '/usr/ucb/ps')
+                                pidtest=`$PSEXE -auxww  $pid | grep "$WRAPPER_CMD" | tail -1`
+                                ;;
+                            '/usr/bin/ps')
+                                TRUNCATED_CMD=`$PSEXE -o comm -p $pid | tail -1`
+                                COUNT=`echo $TRUNCATED_CMD | wc -m`
+                                COUNT=`echo ${COUNT}`
+                                COUNT=`expr $COUNT - 1`
+                                TRUNCATED_CMD=`echo $WRAPPER_CMD | cut -c1-$COUNT`
+                                pidtest=`$PSEXE -o comm -p $pid | grep "$TRUNCATED_CMD" | tail -1`
+                                ;;
+                            '/bin/ps')
+                                TRUNCATED_CMD=`$PSEXE -o comm -p $pid | tail -1`
+                                COUNT=`echo $TRUNCATED_CMD | wc -m`
+                                COUNT=`echo ${COUNT}`
+                                COUNT=`expr $COUNT - 1`
+                                TRUNCATED_CMD=`echo $WRAPPER_CMD | cut -c1-$COUNT`
+                                pidtest=`$PSEXE -o comm -p $pid | grep "$TRUNCATED_CMD" | tail -1`
+                                ;;
+                            *)
+                                echo "Unsupported ps command $PSEXE"
+                                exit 1
+                                ;;
+                            esac
+                        fi
                         ;;
                     'hpux')
                         pidtest=`$PSEXE -p $pid -x -o args | grep "$WRAPPER_CMD" | tail -1`
@@ -560,8 +591,22 @@ getstatus() {
 
 testpid() {
     case "$DIST_OS" in
-    'solaris')
-        pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1` 2>/dev/null
+     'solaris')
+        case "$PSEXE" in
+        '/usr/ucb/ps')
+            pid=`$PSEXE  $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+            ;;
+        '/usr/bin/ps')
+            pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+            ;;
+        '/bin/ps')
+            pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+            ;;
+        *)
+            echo "Unsupported ps command $PSEXE"
+            exit 1
+            ;;
+        esac
         ;;
     *)
         pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1` 2>/dev/null
