Add support for MacOSX Universal Binary distributions.

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -179,28 +179,60 @@ case "$DIST_ARCH" in
         ;;
 esac
 
-# Decide on a detailed wrapper name
-WRAPPER_LONG32_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-WRAPPER_LONG64_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-
+# Decide on the wrapper binary to use.
 # If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
 #  platforms, if the 64-bit binary exists then the distribution most
 #  likely wants to use long names.  Otherwise, look for the default.
-if [ -x $WRAPPER_LONG32_CMD ]
+# For macosx, we also want to look for universal binaries.
+WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+if [ -x $WRAPPER_TEST_CMD ]
 then
-    WRAPPER_CMD="$WRAPPER_LONG32_CMD"
+    WRAPPER_CMD="$WRAPPER_TEST_CMD"
 else
-    if [ -x $WRAPPER_LONG64_CMD ]
+    if [ "$DIST_OS" = "macosx" ]
     then
-        WRAPPER_CMD="$WRAPPER_LONG64_CMD"
-    else
-        if [ ! -x $WRAPPER_CMD ]
+        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
+        if [ -x $WRAPPER_TEST_CMD ]
         then
-            echo "Unable to locate any of the following binaries:"
-            echo "  $WRAPPER_LONG32_CMD"
-            echo "  $WRAPPER_LONG64_CMD"
-            echo "  $WRAPPER_CMD"
-            exit 1
+            WRAPPER_CMD="$WRAPPER_TEST_CMD"
+        else
+            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+            if [ -x $WRAPPER_TEST_CMD ]
+            then
+                WRAPPER_CMD="$WRAPPER_TEST_CMD"
+            else
+                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
+                if [ -x $WRAPPER_TEST_CMD ]
+                then
+                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
+                else
+                    if [ ! -x $WRAPPER_CMD ]
+                    then
+                        echo "Unable to locate any of the following binaries:"
+                        echo "  $WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+                        echo "  $WRAPPER_CMD-$DIST_OS-universal-32"
+                        echo "  $WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+                        echo "  $WRAPPER_CMD-$DIST_OS-universal-64"
+                        echo "  $WRAPPER_CMD"
+                        exit 1
+                    fi
+                fi
+            fi
+        fi
+    else
+        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+        if [ -x $WRAPPER_TEST_CMD ]
+        then
+            WRAPPER_CMD="$WRAPPER_TEST_CMD"
+        else
+            if [ ! -x $WRAPPER_CMD ]
+            then
+                echo "Unable to locate any of the following binaries:"
+                echo "  $WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+                echo "  $WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+                echo "  $WRAPPER_CMD"
+                exit 1
+            fi
         fi
     fi
 fi
