3.5.31 Release

diff --git a/wrapper/src/bin/sh.script.in b/wrapper/src/bin/sh.script.in
--- a/wrapper/src/bin/sh.script.in
+++ b/wrapper/src/bin/sh.script.in
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 #
-# Copyright (c) 1999, 2016 Tanuki Software, Ltd.
+# Copyright (c) 1999, 2017 Tanuki Software, Ltd.
 # http://www.tanukisoftware.com
 # All rights reserved.
 #
@@ -16,7 +16,7 @@
 
 #-----------------------------------------------------------------------------
 # These settings can be modified to fit the needs of your application
-# Optimized for use with version 3.5.31-a of the Wrapper.
+# Optimized for use with version 3.5.31 of the Wrapper.
 
 # IMPORTANT - Please always stop and uninstall an application before making
 #             any changes to this file.  Failure to do so could remove the
@@ -1050,7 +1050,7 @@ launchinternal() {
         prepAdditionalParams "$@"
 
         # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31-a $ADDITIONAL_PARA"
+        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31 $ADDITIONAL_PARA"
         eval $COMMAND_LINE
     else
         eval echo `gettext '$APP_LONG_NAME is already running.'`
@@ -1073,7 +1073,7 @@ console() {
         prepAdditionalParams "$@"
 
         # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" $APPNAMEPROP $ANCHORPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31-a $ADDITIONAL_PARA"
+        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" $APPNAMEPROP $ANCHORPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31 $ADDITIONAL_PARA"
         eval $COMMAND_LINE
         COMMAND_EXIT_CODE=$?
         if [ $COMMAND_EXIT_CODE -ne 0 ] ; then
@@ -1408,7 +1408,7 @@ start() {
         prepAdditionalParams "$@"
 
         # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31-a $ADDITIONAL_PARA"
+        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $APPNAMEPROP $ANCHORPROP $IGNOREPROP $STATUSPROP $COMMANDPROP $LOCKPROP wrapper.script.version=3.5.31 $ADDITIONAL_PARA"
         eval $COMMAND_LINE
     else
         eval echo `gettext '$APP_LONG_NAME is already running.'`
@@ -1513,9 +1513,20 @@ pause() {
     else
         if [ "$PAUSABLE_MODE" = "file" ] ; then
             echo "PAUSE" >> $COMMANDFILE
+            if [ $? != 0 ] ; then
+                eval echo `gettext 'Failed to write in the command file to pause $APP_LONG_NAME.'`
+                exit 1
+            fi
         else
-            # send a SIGUSR1
-            kill -10 $pid
+            # send a SIGUSR1 (use constants because numbers change depending on the platform)
+            kill -USR1 $pid 2>/dev/null
+            if [ $? != 0 ] ; then
+                kill -SIGUSR1 $pid
+                if [ $? != 0 ] ; then
+                    eval echo `gettext 'Failed to send a signal to pause $APP_LONG_NAME.'`
+                    exit 1
+                fi
+            fi
         fi
         eval echo `gettext 'Pausing $APP_LONG_NAME.'`
     fi
@@ -1529,9 +1540,20 @@ resume() {
     else
         if [ "$PAUSABLE_MODE" = "file" ] ; then
             echo "RESUME" >> $COMMANDFILE
+            if [ $? != 0 ] ; then
+                eval echo `gettext 'Failed to write in the command file to resume $APP_LONG_NAME.'`
+                exit 1
+            fi
         else
-            # send a SIGUSR2
-            kill -12 $pid
+            # send a SIGUSR2 (use constants because numbers change depending on the platform)
+            kill -USR2 $pid 2>/dev/null
+            if [ $? != 0 ] ; then
+                kill -SIGUSR2 $pid
+                if [ $? != 0 ] ; then
+                    eval echo `gettext 'Failed to send a signal to resume $APP_LONG_NAME.'`
+                    exit 1
+                fi
+            fi
         fi
         eval echo `gettext 'Resuming $APP_LONG_NAME.'`
     fi
